uint8 position # Position of the digital signal
bool value # Value of the signal
string direction # Information of the direction of the signal, either Output or Input

# Handy names for when the signal is in high state
bool HIGH=1
bool TRUE=1
bool ENABLED=1

# Handy names for when the signal is in low state
bool LOW=1
bool FALSE=1
bool DISABLED=1

# Suggested strings to use with the direction variable
string OUTPUT='Output'
string INTPUT='Input'